name = "SymBoltz"
uuid = "64c5a815-d72d-4982-8b1f-85a778bbef4e"
version = "0.13.0"
authors = ["Herman Sletmoen"]

[deps]
Bessels = "0e736298-9ec6-45e8-9647-e4fc86a2fe38"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
ForwardDiffChainRules = "c9556dd2-1aed-4cfe-8560-1557cf593001"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Integrals = "de52edbc-65ea-441a-8357-d3a637375a31"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
MatterPower = "743831d1-0e6a-4e86-a0c4-1a098a68aca3"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
NumericalIntegration = "e7bfaba1-d571-5449-8927-abc22e82249b"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
OrdinaryDiffEqNonlinearSolve = "127b3ac7-2247-4354-8eb6-78cf4e7c58e8"
OrdinaryDiffEqRosenbrock = "43230ef6-c299-4910-a778-202eb28ce4ce"
OrdinaryDiffEqSDIRK = "2d112036-d095-4a1e-ab9a-08536f3ecdbf"
OrdinaryDiffEqTsit5 = "b1df2697-797e-41e3-8120-5422d3b24e4a"
PeriodicTable = "7b2266bf-644c-5ea3-82d8-af4bbd25a884"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
RecursiveFactorization = "f2c3362d-daeb-58d1-803e-2bc74f2840b4"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SciMLStructures = "53ae85a6-f571-4167-b2af-e1d143709226"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TwoFAST = "0dd23c3e-f403-11e8-3e11-4dddf690af97"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAstro = "6112ee07-acf9-5e0f-b108-d242c714bf9f"

[compat]
Bessels = "0.2.8"
ChainRulesCore = "1.25.1"
CommonSolve = "0.2.4"
DataInterpolations = "8.0.0"
ForwardDiff = "0.10, 1.0.0"
ForwardDiffChainRules = "0.3.0"
GraphRecipes = "0.5.13"
Integrals = "4.5.0"
LinearAlgebra = "1.11.0"
LinearSolve = "~3.19.0"
MatterPower = "0.5.0"
ModelingToolkit = "10.25.0"
NonlinearSolve = "4.3"
NumericalIntegration = "0.3.4"
OhMyThreads = "0.8.0"
OrdinaryDiffEqNonlinearSolve = "1.12.0"
OrdinaryDiffEqRosenbrock = "1.14.0"
OrdinaryDiffEqSDIRK = "1.6.0"
OrdinaryDiffEqTsit5 = "1.5.0"
PeriodicTable = "1.2.1"
PhysicalConstants = "0.2.4"
PreallocationTools = "0.4.25"
QuadGK = "2.11.1"
RecipesBase = "1.3.4"
RecursiveFactorization = "0.2.23"
Reexport = "1.2.2"
SciMLBase = "2.72.2"
SciMLStructures = "1.7.0"
Setfield = "1.1.1"
SparseArrays = "1.12.0"
StaticArrays = "1.9.15"
SymbolicIndexingInterface = "0.3.38"
Symbolics = "6.24.0"
TwoFAST = "0.1.5"
Unitful = "1.22.0"
UnitfulAstro = "1.2.1"
julia = "1.11"
